# Site settings
title: Max L.
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://maxle.netlify.app # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Max L.
user_title : A.I. Software Developer
user_description:

    "Techno-optimist software developer.<br> Embracing AI."
    
 
email: xxx@icloud.com
twitter_username: lorem_ipsum
github_username:  Max-le
gplus_username:  lorem_ipsum

#Permalink : https://jekyllrb.com/docs/permalinks/
permalink: /:year/:title



exclude: ['package.json', 'src' , 'node_modules']
