# Site settings
title: Max Lepin
description: The blog of a Tech enthouiast & lifelong-learner
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "max-le.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Max Lepin
user_title : Java-Angular Developer
user_description: Hi ! This is the blog and personal website of a Tech enthouiast & lifelong-learner.
email: max.09@outlook.com
twitter_username: lorem_ipsum
github_username:  Max-le
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
