# Site settings
title: Max Lepin
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: http://max-le.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Max Lepin
user_title : Full-Stack Software Developer
user_description:

 "Hi ! Welcome to my personal website.<br><br>

I'm a software developer from Brussels, Belgium with more than three years of professional work in the field of IT. <br>

I've gained solid experience in software design, testing, learning and practicing the top industry standards,
 collaboration and successful teamworking.
Here are a few technologies I'm proficient with :"
email: max.09@outlook.com
twitter_username: lorem_ipsum
github_username:  Max-le
gplus_username:  lorem_ipsum

#Permalink : https://jekyllrb.com/docs/permalinks/
permalink: /:year/:title

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
