# Site settings
title: Max Lepin
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://www.maxle.be # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Max Lepin
user_title : Full-Stack Software Developer
user_description:

    "Hi ! Welcome to my website.<br>

    I'm a software developer from Belgium.<br>

    I've gained solid experience in software design, testing, applying the industry standards,
    collaboration and successful team-working."
    
 
email: max.lepin@outlook.com
twitter_username: lorem_ipsum
github_username:  Max-le
gplus_username:  lorem_ipsum

#Permalink : https://jekyllrb.com/docs/permalinks/
permalink: /:year/:title



exclude: ['package.json', 'src' , 'node_modules']
