# Site settings
title: Max Lepin
description: My personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://maxle.netlify.app # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Max Lepin
user_title : A.I. Software Developer
user_description:

    "Hi ! Welcome to my website.<br>

    I'm a software developer from Belgium.<br>

    I use AI to code better and faster. I integrate AI to projects. Check examples below 🙂"
    
 
email: maxlepin@icloud.com
twitter_username: lorem_ipsum
github_username:  Max-le
gplus_username:  lorem_ipsum

#Permalink : https://jekyllrb.com/docs/permalinks/
permalink: /:year/:title



exclude: ['package.json', 'src' , 'node_modules']
